export default function Return() {
  
  return (
    <>
        <div className="text-center">
            <h2>Politica de Privacidade</h2>
        </div>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum  aliquet, sapien blandit condimentum hendrerit, metus felis mollis augue,  non dictum ex augue luctus ligula. Sed ultrices, dolor nec viverra  consectetur, risus mi facilisis lorem, eu suscipit nunc tortor vitae  eros. Duis ipsum ipsum, luctus et felis vel, placerat ultricies odio. In  viverra nisl quis elit pulvinar ultrices ac sed augue. Sed gravida  lobortis justo, quis viverra sem vulputate et. Mauris vehicula euismod  lorem, rutrum sodales arcu gravida vitae. Cras sit amet tempus nulla.  Nulla malesuada et felis eu aliquam. Suspendisse pellentesque, quam ac  fringilla luctus, lorem sem aliquam turpis, sit amet lobortis diam  ligula sit amet neque. Cras suscipit fringilla neque. Fusce convallis ex  massa, in blandit neque rutrum sit amet.

            Sed porttitor eget sapien non commodo. In scelerisque sem lectus, ut  pulvinar lorem faucibus eu. Vestibulum ante ipsum primis in faucibus  orci luctus et ultrices posuere cubilia curae; Nunc vel vulputate neque.  Orci varius natoque penatibus et magnis dis parturient montes, nascetur  ridiculus mus. Aenean at rutrum velit, eu pulvinar sem. Nam vel lectus  ipsum. Cras mauris nulla, rutrum at arcu non, mollis faucibus ante. Ut  augue sem, accumsan eu nibh id, pretium gravida libero. Donec pharetra  semper rhoncus. Phasellus augue nisi, congue eget lobortis eu, elementum  scelerisque est. Donec imperdiet nunc quis est aliquet placerat. Donec  in mi placerat, rhoncus metus a, facilisis arcu.

            Pellentesque aliquet justo eu faucibus dignissim. Etiam vestibulum velit  quis tortor feugiat imperdiet. Pellentesque eget arcu id enim accumsan  iaculis. Nullam nec dui et nisi suscipit auctor ac iaculis tellus.  Curabitur at ex ac dui congue tristique. Donec commodo orci id risus  elementum, pellentesque sollicitudin eros porttitor. Praesent  pellentesque, metus eget mattis suscipit, metus odio tempor turpis, a  mattis velit orci vel augue.

            Morbi vulputate elit vehicula massa accumsan tristique. Vestibulum ac  diam a odio euismod porta at eget quam. Cras rutrum faucibus elit eget  lobortis. Nunc tempus tellus vel leo dapibus, vulputate imperdiet velit  bibendum. Nunc mollis, augue a aliquet ultricies, erat elit placerat  ligula, a lobortis lacus ante in nisl. Phasellus id euismod metus. Nunc  ipsum orci, pellentesque non sem quis, condimentum posuere leo.  Phasellus a velit in metus consectetur malesuada. Proin blandit arcu  lectus, at auctor risus luctus in. Donec et nisi mi.

            Pellentesque aliquam, metus nec eleifend faucibus, mi mauris scelerisque  arcu, quis blandit lacus diam ut tellus. Sed non lorem dui. Maecenas ac  pretium nulla, nec pellentesque nunc. Phasellus rhoncus ultricies dolor  at dictum. Quisque semper neque non cursus eleifend. Donec vitae  aliquam ante. Ut interdum mollis enim nec lacinia. Maecenas ut mauris in  felis mattis semper. Ut pellentesque ante sed lobortis placerat. Aenean  consequat quis quam sagittis condimentum. Quisque et nisl lectus. Nam  ultricies libero est, a semper est varius eget. Nullam sollicitudin  nulla elit, et malesuada ante tristique ornare. Quisque vitae quam sed  libero molestie blandit vitae eget enim.

            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum  aliquet, sapien blandit condimentum hendrerit, metus felis mollis augue,  non dictum ex augue luctus ligula. Sed ultrices, dolor nec viverra  consectetur, risus mi facilisis lorem, eu suscipit nunc tortor vitae  eros. Duis ipsum ipsum, luctus et felis vel, placerat ultricies odio. In  viverra nisl quis elit pulvinar ultrices ac sed augue. Sed gravida  lobortis justo, quis viverra sem vulputate et. Mauris vehicula euismod  lorem, rutrum sodales arcu gravida vitae. Cras sit amet tempus nulla.  Nulla malesuada et felis eu aliquam. Suspendisse pellentesque, quam ac  fringilla luctus, lorem sem aliquam turpis, sit amet lobortis diam  ligula sit amet neque. Cras suscipit fringilla neque. Fusce convallis ex  massa, in blandit neque rutrum sit amet.

            Sed porttitor eget sapien non commodo. In scelerisque sem lectus, ut  pulvinar lorem faucibus eu. Vestibulum ante ipsum primis in faucibus  orci luctus et ultrices posuere cubilia curae; Nunc vel vulputate neque.  Orci varius natoque penatibus et magnis dis parturient montes, nascetur  ridiculus mus. Aenean at rutrum velit, eu pulvinar sem. Nam vel lectus  ipsum. Cras mauris nulla, rutrum at arcu non, mollis faucibus ante. Ut  augue sem, accumsan eu nibh id, pretium gravida libero. Donec pharetra  semper rhoncus. Phasellus augue nisi, congue eget lobortis eu, elementum  scelerisque est. Donec imperdiet nunc quis est aliquet placerat. Donec  in mi placerat, rhoncus metus a, facilisis arcu.

            Pellentesque aliquet justo eu faucibus dignissim. Etiam vestibulum velit  quis tortor feugiat imperdiet. Pellentesque eget arcu id enim accumsan  iaculis. Nullam nec dui et nisi suscipit auctor ac iaculis tellus.  Curabitur at ex ac dui congue tristique. Donec commodo orci id risus  elementum, pellentesque sollicitudin eros porttitor. Praesent  pellentesque, metus eget mattis suscipit, metus odio tempor turpis, a  mattis velit orci vel augue.

            Morbi vulputate elit vehicula massa accumsan tristique. Vestibulum ac  diam a odio euismod porta at eget quam. Cras rutrum faucibus elit eget  lobortis. Nunc tempus tellus vel leo dapibus, vulputate imperdiet velit  bibendum. Nunc mollis, augue a aliquet ultricies, erat elit placerat  ligula, a lobortis lacus ante in nisl. Phasellus id euismod metus. Nunc  ipsum orci, pellentesque non sem quis, condimentum posuere leo.  Phasellus a velit in metus consectetur malesuada. Proin blandit arcu  lectus, at auctor risus luctus in. Donec et nisi mi.

            Pellentesque aliquam, metus nec eleifend faucibus, mi mauris scelerisque  arcu, quis blandit lacus diam ut tellus. Sed non lorem dui. Maecenas ac  pretium nulla, nec pellentesque nunc. Phasellus rhoncus ultricies dolor  at dictum. Quisque semper neque non cursus eleifend. Donec vitae  aliquam ante. Ut interdum mollis enim nec lacinia. Maecenas ut mauris in  felis mattis semper. Ut pellentesque ante sed lobortis placerat. Aenean  consequat quis quam sagittis condimentum. Quisque et nisl lectus. Nam  ultricies libero est, a semper est varius eget. Nullam sollicitudin  nulla elit, et malesuada ante tristique ornare. Quisque vitae quam sed  libero molestie blandit vitae eget enim.
        </p>
    </>
  );
}
